MsgBox "Do you want to install Microsoft Office 2016?", 4+32, "Microsoft Office 2016"
MsgBox "This installation package is sponsored by IcebergCP.", 0+64, "Go to icebergcp.com"
MsgBox "WARNING: The version of Windows you're using is incompatible with Office 2016!", 0+48, "Office 2016 cannot be installed"
MsgBox "You can get Office 2016 if you install Windows 10. Do you want to install Windows 10 and proceed with Office 2016 installation?", 4+32, "Upgrade to Windows 10"
MsgBox "Sorry, you cannot upgrade from this version of Windows.", 0+16, "Office 2016 could not be installed."
